version: '3'
networks:
  opencart-dev-tier:
    driver: bridge

services:
  web:
    image: nginx:1.23.2
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "../upload:/app"
    networks:
      - opencart-dev-tier
  php:
    image: ccr.ccs.tencentyun.com/tutiao.info/php-dev:1.0.0
    volumes:
      - '../develop/app/php.ini:/usr/local/etc/php/php.ini'
      - '../upload:/app'
      - '../develop/app/config.php:/app/config.php'
      - '../develop/app/admin/config.php:/app/admin/config.php'
    ports:
      - 9000:9000
    networks:
      - opencart-dev-tier

